name: "swift-iid-DBA-0" # experiment name
description: SWIFT # experiment description
model: "res" # model name: res/VGG/wrn
comm_style: "swift" # baseline communicator
resSize: 18 # res net size
lr: 0.1 # learning rate to start from (if not customLR then lr always 0.1)
momentum: 0.9 # momentum
epoch: 200 #200 # total epoch
bs: 32 # batch size on each worker
noniid: 0 # use non iid data or not
degree_noniid: 0 # how distributed are labels (0 is random)
weight_type: "swift" # how do workers average with each other
unordered_epochs: 1 # calculate consensus after the first n models

# Poisoning arguments
adv_list: [1, 10, 20, 30] # list of adversaries
adv_mode: "regular"
adv_method: "DBA"
attack_interval: 3
# Single shot
# adv_epoch: [[2], [4], [6], [8]] # list of epochs to poison
# Multi shot
adv_epoch: [[], 
            [], 
            [], 
            []] # list of epochs to poison
poison_patterns: [[[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],  # TODO: Overlap
                  [[0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14]], 
                  [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5]], 
                  [[4, 9], [4, 10], [4, 11], [4, 12], [4, 13], [4, 14]]] # list of poison patterns
trigger_num: 4 # number of triggers
poison_label_swap: [2] # label swap
poison_labels: ['all']
poisoning_per_batch: 5 # poisoning per batch

# Specific async arguments
wb: 1 # proportionally increase neighbor weights or self replace
memory_efficient: 0 # DO store all neighbor local models
max_sgd: 10 # max sgd steps per worker
personalize: 0 # use personalization or not
i1: 0 # i1 comm set, number of local updates no averaging
i2: 1 # i2 comm set, number of d-sgd updates
sgd_steps: 2 # baseline sgd steps per worker
num_clusters: 1 # number of clusters in graph
graph: "ring" # graph topology
warmup: false # use lr warmup or not
nesterov: false # use nesterov momentum or not
dataset: "cifar10" # the dataset
datasetRoot: "/home/bhui/bohan/DBA-SWIFT/Data" # the path of dataset
downloadCifar: 0 # change to 1 if needing to download Cifar
p: false # partition the dataset or not
savePath: null # save path
outputFolder: "/home/bhui/bohan/DBA-SWIFT/Output" # save folder
randomSeed: 9000 # random seed
customLR: 1 # custom learning rate strategy, 1 if using multi-step

# mpirun --oversubscribe -np 40 python Train.py --config Config/swift-iid-DBA-0.yaml --randomSeed 100